GFXLIBS => ESTAR_GFXLIBS and ENABLE_GFX => ESTAR_ENABLE_GFX
git-svn-id: https://estar.svn.sourceforge.net/svnroot/estar/trunk/estar@123 255146f7-950e-0410-bd4e-f0acf59374a5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -860,9 +860,9 @@ am__fastdepCXX_FALSE
 CXXCPP
 GREP
 EGREP
-ENABLE_GFX_TRUE
-ENABLE_GFX_FALSE
-GFXLIBS
+ESTAR_ENABLE_GFX_TRUE
+ESTAR_ENABLE_GFX_FALSE
+ESTAR_GFXLIBS
 LN_S
 ECHO
 AR
@@ -4079,12 +4079,11 @@ else
 fi
 
 
-
 case "$host_os" in
   linux*)  { echo "$as_me:$LINENO: detected Linux" >&5
 echo "$as_me: detected Linux" >&6;}
            ESTAR_CPPFLAGS="$ESTAR_CPPFLAGS -DLINUX"
-           GFXLIBS="-L/usr/X11R6/lib -lglut -lGLU -lGL -lXi -lXmu"
+           ESTAR_GFXLIBS="-L/usr/X11R6/lib -lglut -lGLU -lGL -lXi -lXmu"
 
 ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -4852,22 +4851,22 @@ if test $ac_cv_header_GL_glut_h = yes; then
 
 
 if true; then
-  ENABLE_GFX_TRUE=
-  ENABLE_GFX_FALSE='#'
+  ESTAR_ENABLE_GFX_TRUE=
+  ESTAR_ENABLE_GFX_FALSE='#'
 else
-  ENABLE_GFX_TRUE='#'
-  ENABLE_GFX_FALSE=
+  ESTAR_ENABLE_GFX_TRUE='#'
+  ESTAR_ENABLE_GFX_FALSE=
 fi
 
 else
 
 
 if false; then
-  ENABLE_GFX_TRUE=
-  ENABLE_GFX_FALSE='#'
+  ESTAR_ENABLE_GFX_TRUE=
+  ESTAR_ENABLE_GFX_FALSE='#'
 else
-  ENABLE_GFX_TRUE='#'
-  ENABLE_GFX_FALSE=
+  ESTAR_ENABLE_GFX_TRUE='#'
+  ESTAR_ENABLE_GFX_FALSE=
 fi
 
 fi
@@ -4877,7 +4876,7 @@ fi
 echo "$as_me: detected OSX" >&6;}
            ESTAR_CPPFLAGS="$ESTAR_CPPFLAGS -DOSX"
            ESTAR_CFLAGS="$ESTAR_CFLAGS -Wno-long-double"
-           GFXLIBS="-framework OpenGL -framework GLUT -lobjc"
+           ESTAR_GFXLIBS="-framework OpenGL -framework GLUT -lobjc"
            if test "${ac_cv_header_GLUT_glut_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for GLUT/glut.h" >&5
 echo $ECHO_N "checking for GLUT/glut.h... $ECHO_C" >&6; }
@@ -5012,22 +5011,22 @@ if test $ac_cv_header_GLUT_glut_h = yes; then
 
 
 if true; then
-  ENABLE_GFX_TRUE=
-  ENABLE_GFX_FALSE='#'
+  ESTAR_ENABLE_GFX_TRUE=
+  ESTAR_ENABLE_GFX_FALSE='#'
 else
-  ENABLE_GFX_TRUE='#'
-  ENABLE_GFX_FALSE=
+  ESTAR_ENABLE_GFX_TRUE='#'
+  ESTAR_ENABLE_GFX_FALSE=
 fi
 
 else
 
 
 if false; then
-  ENABLE_GFX_TRUE=
-  ENABLE_GFX_FALSE='#'
+  ESTAR_ENABLE_GFX_TRUE=
+  ESTAR_ENABLE_GFX_FALSE='#'
 else
-  ENABLE_GFX_TRUE='#'
-  ENABLE_GFX_FALSE=
+  ESTAR_ENABLE_GFX_TRUE='#'
+  ESTAR_ENABLE_GFX_FALSE=
 fi
 
 fi
@@ -5924,7 +5923,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5927 "configure"' > conftest.$ac_ext
+  echo '#line 5926 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7939,11 +7938,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7942: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7941: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7946: \$? = $ac_status" >&5
+   echo "$as_me:7945: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8207,11 +8206,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8210: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8209: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8214: \$? = $ac_status" >&5
+   echo "$as_me:8213: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8311,11 +8310,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8314: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8313: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8318: \$? = $ac_status" >&5
+   echo "$as_me:8317: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10619,7 +10618,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10622 "configure"
+#line 10621 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10719,7 +10718,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10722 "configure"
+#line 10721 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13055,11 +13054,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13058: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13057: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13062: \$? = $ac_status" >&5
+   echo "$as_me:13061: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13159,11 +13158,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13162: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13161: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13166: \$? = $ac_status" >&5
+   echo "$as_me:13165: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14729,11 +14728,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14732: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14731: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14736: \$? = $ac_status" >&5
+   echo "$as_me:14735: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14833,11 +14832,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14836: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14835: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14840: \$? = $ac_status" >&5
+   echo "$as_me:14839: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17031,11 +17030,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17034: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17033: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17038: \$? = $ac_status" >&5
+   echo "$as_me:17037: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17299,11 +17298,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17302: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17301: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17306: \$? = $ac_status" >&5
+   echo "$as_me:17305: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17403,11 +17402,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17406: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17405: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17410: \$? = $ac_status" >&5
+   echo "$as_me:17409: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20328,31 +20327,31 @@ echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${ENABLE_GFX_TRUE}" && test -z "${ENABLE_GFX_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_GFX\" was never defined.
+if test -z "${ESTAR_ENABLE_GFX_TRUE}" && test -z "${ESTAR_ENABLE_GFX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ESTAR_ENABLE_GFX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"ENABLE_GFX\" was never defined.
+echo "$as_me: error: conditional \"ESTAR_ENABLE_GFX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${ENABLE_GFX_TRUE}" && test -z "${ENABLE_GFX_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_GFX\" was never defined.
+if test -z "${ESTAR_ENABLE_GFX_TRUE}" && test -z "${ESTAR_ENABLE_GFX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ESTAR_ENABLE_GFX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"ENABLE_GFX\" was never defined.
+echo "$as_me: error: conditional \"ESTAR_ENABLE_GFX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${ENABLE_GFX_TRUE}" && test -z "${ENABLE_GFX_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_GFX\" was never defined.
+if test -z "${ESTAR_ENABLE_GFX_TRUE}" && test -z "${ESTAR_ENABLE_GFX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ESTAR_ENABLE_GFX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"ENABLE_GFX\" was never defined.
+echo "$as_me: error: conditional \"ESTAR_ENABLE_GFX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${ENABLE_GFX_TRUE}" && test -z "${ENABLE_GFX_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_GFX\" was never defined.
+if test -z "${ESTAR_ENABLE_GFX_TRUE}" && test -z "${ESTAR_ENABLE_GFX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ESTAR_ENABLE_GFX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"ENABLE_GFX\" was never defined.
+echo "$as_me: error: conditional \"ESTAR_ENABLE_GFX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -20984,9 +20983,9 @@ am__fastdepCXX_FALSE!$am__fastdepCXX_FALSE$ac_delim
 CXXCPP!$CXXCPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
-ENABLE_GFX_TRUE!$ENABLE_GFX_TRUE$ac_delim
-ENABLE_GFX_FALSE!$ENABLE_GFX_FALSE$ac_delim
-GFXLIBS!$GFXLIBS$ac_delim
+ESTAR_ENABLE_GFX_TRUE!$ESTAR_ENABLE_GFX_TRUE$ac_delim
+ESTAR_ENABLE_GFX_FALSE!$ESTAR_ENABLE_GFX_FALSE$ac_delim
+ESTAR_GFXLIBS!$ESTAR_GFXLIBS$ac_delim
 LN_S!$LN_S$ac_delim
 ECHO!$ECHO$ac_delim
 AR!$AR$ac_delim
@@ -21641,16 +21640,16 @@ fi
 echo "$as_me: ==================================================" >&6;}
 { echo "$as_me:$LINENO: Configuration Summary:" >&5
 echo "$as_me: Configuration Summary:" >&6;}
-if test -z "$ENABLE_GFX_TRUE"; then
-  { echo "$as_me:$LINENO:   ENABLE_GFX: true - graphical components will be built" >&5
-echo "$as_me:   ENABLE_GFX: true - graphical components will be built" >&6;}
-  { echo "$as_me:$LINENO:   GFXLIBS: $GFXLIBS" >&5
-echo "$as_me:   GFXLIBS: $GFXLIBS" >&6;}
+if test -z "$ESTAR_ENABLE_GFX_TRUE"; then
+  { echo "$as_me:$LINENO:   ESTAR_ENABLE_GFX: true - graphical components will be built" >&5
+echo "$as_me:   ESTAR_ENABLE_GFX: true - graphical components will be built" >&6;}
+  { echo "$as_me:$LINENO:   ESTAR_GFXLIBS: $ESTAR_GFXLIBS" >&5
+echo "$as_me:   ESTAR_GFXLIBS: $ESTAR_GFXLIBS" >&6;}
 else
-  { echo "$as_me:$LINENO:   ENABLE_GFX: false - skip graphical components" >&5
-echo "$as_me:   ENABLE_GFX: false - skip graphical components" >&6;}
-  { echo "$as_me:$LINENO:   GFXLIBS: $GFXLIBS" >&5
-echo "$as_me:   GFXLIBS: $GFXLIBS" >&6;}
+  { echo "$as_me:$LINENO:   ESTAR_ENABLE_GFX: false - skip graphical components" >&5
+echo "$as_me:   ESTAR_ENABLE_GFX: false - skip graphical components" >&6;}
+  { echo "$as_me:$LINENO:   ESTAR_GFXLIBS: $ESTAR_GFXLIBS" >&5
+echo "$as_me:   ESTAR_GFXLIBS: $ESTAR_GFXLIBS" >&6;}
 fi
 { echo "$as_me:$LINENO:   ESTAR_CPPFLAGS: $ESTAR_CPPFLAGS" >&5
 echo "$as_me:   ESTAR_CPPFLAGS: $ESTAR_CPPFLAGS" >&6;}
