Better check for boost (includes graph library), summary config info at the end of configure.
git-svn-id: https://estar.svn.sourceforge.net/svnroot/estar/trunk/estar@120 255146f7-950e-0410-bd4e-f0acf59374a5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1476,6 +1476,7 @@ Optional Features:
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-debug          GCC options -g -O0 (else -O3)
+  --enable-pedantic       GCC options -pedantic (else -Wall)
   --enable-static[=PKGS]  build static libraries [default=no]
   --enable-shared[=PKGS]  build shared libraries [default=no]
   --enable-fast-install[=PKGS]
@@ -4070,9 +4071,18 @@ else
 fi
 
 
+# Check whether --enable-pedantic was given.
+if test "${enable_pedantic+set}" = set; then
+  enableval=$enable_pedantic;  ESTAR_CFLAGS="$ESTAR_CFLAGS -pedantic"
+else
+   ESTAR_CFLAGS="$ESTAR_CFLAGS -Wall"
+fi
+
+
+
 case "$host_os" in
-  linux*)  { echo "$as_me:$LINENO: result: detected Linux" >&5
-echo "${ECHO_T}detected Linux" >&6; }
+  linux*)  { echo "$as_me:$LINENO: detected Linux" >&5
+echo "$as_me: detected Linux" >&6;}
            ESTAR_CPPFLAGS="$ESTAR_CPPFLAGS -DLINUX"
            GFXLIBS="-L/usr/X11R6/lib -lglut -lGLU -lGL -lXi -lXmu"
 
@@ -4863,8 +4873,8 @@ fi
 fi
 
 ;;
-  darwin*) { echo "$as_me:$LINENO: result: detected OSX" >&5
-echo "${ECHO_T}detected OSX" >&6; }
+  darwin*) { echo "$as_me:$LINENO: detected OSX" >&5
+echo "$as_me: detected OSX" >&6;}
            ESTAR_CPPFLAGS="$ESTAR_CPPFLAGS -DOSX"
            ESTAR_CFLAGS="$ESTAR_CFLAGS -Wno-long-double"
            GFXLIBS="-framework OpenGL -framework GLUT -lobjc"
@@ -5034,7 +5044,7 @@ esac
 if test "${with_boost+set}" = set; then
   withval=$with_boost;  if test "x$withval" != "x" ; then
       ESTAR_CPPFLAGS="$ESTAR_CPPFLAGS -I${withval}/include -I${withval}"
-      ESTAR_LDFLAGS="-L${withval}/lib -I${withval} $ESTAR_LDFLAGS"
+      ESTAR_LDFLAGS="-L${withval}/lib $ESTAR_LDFLAGS"
     fi
 fi
 
@@ -5174,8 +5184,160 @@ if test $ac_cv_header_boost_shared_ptr_hpp = yes; then
   :
 else
 
-  { { echo "$as_me:$LINENO: error: cannot compile boost/shared_ptr.hpp (CPPFLAGS=$CPPFLAGS)" >&5
-echo "$as_me: error: cannot compile boost/shared_ptr.hpp (CPPFLAGS=$CPPFLAGS)" >&2;}
+  { echo "$as_me:$LINENO: failed to find boost smart pointer library:" >&5
+echo "$as_me: failed to find boost smart pointer library:" >&6;}
+  { echo "$as_me:$LINENO:   cannot compile boost/shared_ptr.hpp" >&5
+echo "$as_me:   cannot compile boost/shared_ptr.hpp" >&6;}
+  { echo "$as_me:$LINENO:   CPPFLAGS=$CPPFLAGS" >&5
+echo "$as_me:   CPPFLAGS=$CPPFLAGS" >&6;}
+  { { echo "$as_me:$LINENO: error:   specify boost library install path (--with-boost=PATH)" >&5
+echo "$as_me: error:   specify boost library install path (--with-boost=PATH)" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+if test "${ac_cv_header_boost_graph_adjacency_list_hpp+set}" = set; then
+  { echo "$as_me:$LINENO: checking for boost/graph/adjacency_list.hpp" >&5
+echo $ECHO_N "checking for boost/graph/adjacency_list.hpp... $ECHO_C" >&6; }
+if test "${ac_cv_header_boost_graph_adjacency_list_hpp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_boost_graph_adjacency_list_hpp" >&5
+echo "${ECHO_T}$ac_cv_header_boost_graph_adjacency_list_hpp" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking boost/graph/adjacency_list.hpp usability" >&5
+echo $ECHO_N "checking boost/graph/adjacency_list.hpp usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <boost/graph/adjacency_list.hpp>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking boost/graph/adjacency_list.hpp presence" >&5
+echo $ECHO_N "checking boost/graph/adjacency_list.hpp presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <boost/graph/adjacency_list.hpp>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: boost/graph/adjacency_list.hpp: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: boost/graph/adjacency_list.hpp: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/graph/adjacency_list.hpp: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: boost/graph/adjacency_list.hpp: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: boost/graph/adjacency_list.hpp: present but cannot be compiled" >&5
+echo "$as_me: WARNING: boost/graph/adjacency_list.hpp: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/graph/adjacency_list.hpp:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: boost/graph/adjacency_list.hpp:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/graph/adjacency_list.hpp: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: boost/graph/adjacency_list.hpp: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/graph/adjacency_list.hpp:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: boost/graph/adjacency_list.hpp:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/graph/adjacency_list.hpp: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: boost/graph/adjacency_list.hpp: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/graph/adjacency_list.hpp: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: boost/graph/adjacency_list.hpp: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ----------------------------------------------------------- ##
+## Report this to estar-devel AT lists DOT sourceforge DOT net ##
+## ----------------------------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for boost/graph/adjacency_list.hpp" >&5
+echo $ECHO_N "checking for boost/graph/adjacency_list.hpp... $ECHO_C" >&6; }
+if test "${ac_cv_header_boost_graph_adjacency_list_hpp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_boost_graph_adjacency_list_hpp=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_boost_graph_adjacency_list_hpp" >&5
+echo "${ECHO_T}$ac_cv_header_boost_graph_adjacency_list_hpp" >&6; }
+
+fi
+if test $ac_cv_header_boost_graph_adjacency_list_hpp = yes; then
+  :
+else
+
+  { echo "$as_me:$LINENO: failed to find boost graph library:" >&5
+echo "$as_me: failed to find boost graph library:" >&6;}
+  { echo "$as_me:$LINENO:   cannot compile boost/graph/adjacency_list.hpp" >&5
+echo "$as_me:   cannot compile boost/graph/adjacency_list.hpp" >&6;}
+  { echo "$as_me:$LINENO:   CPPFLAGS=$CPPFLAGS" >&5
+echo "$as_me:   CPPFLAGS=$CPPFLAGS" >&6;}
+  { { echo "$as_me:$LINENO: error:   specify boost library install path (--with-boost=PATH)" >&5
+echo "$as_me: error:   specify boost library install path (--with-boost=PATH)" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -5762,7 +5924,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5765 "configure"' > conftest.$ac_ext
+  echo '#line 5927 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7777,11 +7939,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7780: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7942: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7784: \$? = $ac_status" >&5
+   echo "$as_me:7946: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8045,11 +8207,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8048: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8210: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8052: \$? = $ac_status" >&5
+   echo "$as_me:8214: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8149,11 +8311,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8152: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8314: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8156: \$? = $ac_status" >&5
+   echo "$as_me:8318: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10457,7 +10619,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10460 "configure"
+#line 10622 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10557,7 +10719,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10560 "configure"
+#line 10722 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12893,11 +13055,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12896: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13058: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12900: \$? = $ac_status" >&5
+   echo "$as_me:13062: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12997,11 +13159,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13000: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13162: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13004: \$? = $ac_status" >&5
+   echo "$as_me:13166: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14567,11 +14729,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14570: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14732: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14574: \$? = $ac_status" >&5
+   echo "$as_me:14736: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14671,11 +14833,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14674: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14836: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14678: \$? = $ac_status" >&5
+   echo "$as_me:14840: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16869,11 +17031,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16872: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17034: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16876: \$? = $ac_status" >&5
+   echo "$as_me:17038: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17137,11 +17299,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17140: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17302: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17144: \$? = $ac_status" >&5
+   echo "$as_me:17306: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17241,11 +17403,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17244: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17406: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17248: \$? = $ac_status" >&5
+   echo "$as_me:17410: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21474,3 +21636,29 @@ if test "$no_create" != yes; then
   $ac_cs_success || { (exit 1); exit 1; }
 fi
 
+
+{ echo "$as_me:$LINENO: ==================================================" >&5
+echo "$as_me: ==================================================" >&6;}
+{ echo "$as_me:$LINENO: Configuration Summary:" >&5
+echo "$as_me: Configuration Summary:" >&6;}
+if test -z "$ENABLE_GFX_TRUE"; then
+  { echo "$as_me:$LINENO:   ENABLE_GFX: true - graphical components will be built" >&5
+echo "$as_me:   ENABLE_GFX: true - graphical components will be built" >&6;}
+  { echo "$as_me:$LINENO:   GFXLIBS: $GFXLIBS" >&5
+echo "$as_me:   GFXLIBS: $GFXLIBS" >&6;}
+else
+  { echo "$as_me:$LINENO:   ENABLE_GFX: false - skip graphical components" >&5
+echo "$as_me:   ENABLE_GFX: false - skip graphical components" >&6;}
+  { echo "$as_me:$LINENO:   GFXLIBS: $GFXLIBS" >&5
+echo "$as_me:   GFXLIBS: $GFXLIBS" >&6;}
+fi
+{ echo "$as_me:$LINENO:   ESTAR_CPPFLAGS: $ESTAR_CPPFLAGS" >&5
+echo "$as_me:   ESTAR_CPPFLAGS: $ESTAR_CPPFLAGS" >&6;}
+{ echo "$as_me:$LINENO:   ESTAR_CFLAGS: $ESTAR_CFLAGS" >&5
+echo "$as_me:   ESTAR_CFLAGS: $ESTAR_CFLAGS" >&6;}
+{ echo "$as_me:$LINENO:   ESTAR_CXXFLAGS: $ESTAR_CXXFLAGS" >&5
+echo "$as_me:   ESTAR_CXXFLAGS: $ESTAR_CXXFLAGS" >&6;}
+{ echo "$as_me:$LINENO:   ESTAR_LDFLAGS: $ESTAR_LDFLAGS" >&5
+echo "$as_me:   ESTAR_LDFLAGS: $ESTAR_LDFLAGS" >&6;}
+{ echo "$as_me:$LINENO: ==================================================" >&5
+echo "$as_me: ==================================================" >&6;}
